import { DocumentModel } from '../types';

export const SAMPLE_DOCUMENT: DocumentModel = {
  id: 'charanjeet-singh-resume',
  title: 'Charanjeet_Singh_Executive_Resume',
  sourceType: 'sample',
  pageCount: 2,
  lastModified: Date.now(),
  originalFileName: 'Charanjeet_Singh_Resume.pdf',
  activeLayoutMode: 'spatial',
  pages: [
    {
      id: 'page-1',
      pageNumber: 1,
      rotation: 0,
      layoutMode: 'spatial',
      hasMultiColumn: true,
      backgroundImageUrl:
        'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="794" height="1123" viewBox="0 0 794 1123"><rect width="794" height="1123" fill="%23ffffff"/><defs><linearGradient id="headerGreenGrad" x1="0%25" y1="0%25" x2="100%25" y2="100%25"><stop offset="0%25" stop-color="%23064e3b" /><stop offset="100%25" stop-color="%23047857" /></linearGradient></defs><rect x="0" y="0" width="794" height="202" fill="url(%23headerGreenGrad)"/><rect x="0" y="198" width="794" height="4" fill="%2310b981"/><circle cx="680" cy="101" r="62" fill="%23047857" stroke="%23ffffff" stroke-width="4"/><circle cx="680" cy="85" r="22" fill="%23f1f5f9"/><path d="M 652 135 C 652 112 708 112 708 135 Z" fill="%23f1f5f9"/><rect x="0" y="202" width="278" height="921" fill="%23f8fafc"/><line x1="278" y1="202" x2="278" y2="1123" stroke="%23e2e8f0" stroke-width="1.5"/><rect x="20" y="226" width="238" height="26" rx="4" fill="%23064e3b"/><rect x="20" y="440" width="238" height="26" rx="4" fill="%23064e3b"/><rect x="20" y="650" width="238" height="26" rx="4" fill="%23064e3b"/><rect x="20" y="850" width="238" height="26" rx="4" fill="%23064e3b"/><rect x="302" y="226" width="468" height="26" rx="4" fill="%23f1f5f9" stroke="%23cbd5e1" stroke-width="1"/><rect x="302" y="226" width="6" height="26" rx="2" fill="%23064e3b"/><rect x="302" y="440" width="468" height="26" rx="4" fill="%23f1f5f9" stroke="%23cbd5e1" stroke-width="1"/><rect x="302" y="440" width="6" height="26" rx="2" fill="%23064e3b"/><rect x="302" y="790" width="468" height="26" rx="4" fill="%23f1f5f9" stroke="%23cbd5e1" stroke-width="1"/><rect x="302" y="790" width="6" height="26" rx="2" fill="%23064e3b"/></svg>',
      thumbnailUrl:
        'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="200" height="280" viewBox="0 0 794 1123"><rect width="794" height="1123" fill="%23ffffff"/><rect x="0" y="0" width="794" height="202" fill="%23064e3b"/><circle cx="680" cy="101" r="50" fill="%23ffffff"/><rect x="0" y="202" width="278" height="921" fill="%23f8fafc"/><line x1="278" y1="202" x2="278" y2="1123" stroke="%23e2e8f0" stroke-width="2"/><rect x="20" y="226" width="238" height="26" rx="4" fill="%23064e3b"/><rect x="20" y="440" width="238" height="26" rx="4" fill="%23064e3b"/><rect x="302" y="226" width="468" height="26" rx="4" fill="%23e2e8f0"/><rect x="302" y="440" width="468" height="26" rx="4" fill="%23e2e8f0"/></svg>',
      blocks: [
        // 1. Top Header Banner (Fixed within 18% Header Container)
        {
          id: 'b-h1',
          type: 'h1',
          content: 'CHARANJEET SINGH',
          align: 'left',
          isBold: true,
          fontSize: 24,
          textColor: '#ffffff',
          x: 5,
          y: 4,
          width: 70,
          isSpatial: true,
          columnGroup: 'header',
        },
        {
          id: 'b-h2',
          type: 'paragraph',
          content: 'RERA Certified Senior Real Estate Consultant & Property Portfolio Advisor',
          align: 'left',
          isBold: false,
          fontSize: 12,
          textColor: '#d1fae5',
          x: 5,
          y: 11,
          width: 70,
          isSpatial: true,
          columnGroup: 'header',
        },

        // 2. Left Sidebar (Fixed within 35% Left Sidebar Container, y >= 18%)
        {
          id: 'b-side-1',
          type: 'h3',
          content: 'CONTACT INFORMATION',
          isBold: true,
          fontSize: 11,
          x: 4,
          y: 20.5,
          width: 27,
          textColor: '#ffffff',
          isSpatial: true,
          columnGroup: 'sidebar',
        },
        {
          id: 'b-side-2',
          type: 'paragraph',
          content: 'Email: Cjeet336@gmail.com\nPhone: +91 98765 43210\nLocation: Gurugram / New Delhi, India\nRERA No: RERA-DLR-2021-A-04829\nLinkedIn: linkedin.com/in/charanjeet-singh',
          fontSize: 9.5,
          x: 4,
          y: 24,
          width: 27,
          isSpatial: true,
          columnGroup: 'sidebar',
        },
        {
          id: 'b-side-3',
          type: 'h3',
          content: 'EDUCATION & LICENSES',
          isBold: true,
          fontSize: 11,
          x: 4,
          y: 39.5,
          width: 27,
          textColor: '#ffffff',
          isSpatial: true,
          columnGroup: 'sidebar',
        },
        {
          id: 'b-side-4',
          type: 'paragraph',
          content: 'Bachelor of Commerce (B.Com Hons.)\nDelhi University (2012 - 2015)\n\nDiploma in Real Estate Investment & Finance\nNational Institute of Real Estate\n\nRERA Authorized Real Estate Agent\nCertified Property Valuer (CPV)',
          fontSize: 9.5,
          x: 4,
          y: 43,
          width: 27,
          isSpatial: true,
          columnGroup: 'sidebar',
        },
        {
          id: 'b-side-5',
          type: 'h3',
          content: 'CORE COMPETENCIES',
          isBold: true,
          fontSize: 11,
          x: 4,
          y: 58.5,
          width: 27,
          textColor: '#ffffff',
          isSpatial: true,
          columnGroup: 'sidebar',
        },
        {
          id: 'b-side-6',
          type: 'paragraph',
          content: '• Luxury Residential Sales\n• Commercial Office Leasing\n• High-Net-Worth Client Advisory\n• Legal Title & Deed Scrutiny\n• Contract Structuring & Negotiation\n• Landlord & Tenant Representation\n• Real Estate Market Valuation\n• RERA Compliance & Due Diligence',
          fontSize: 9.5,
          x: 4,
          y: 62,
          width: 27,
          isSpatial: true,
          columnGroup: 'sidebar',
        },
        {
          id: 'b-side-7',
          type: 'h3',
          content: 'LANGUAGES & TOOLS',
          isBold: true,
          fontSize: 11,
          x: 4,
          y: 76.5,
          width: 27,
          textColor: '#ffffff',
          isSpatial: true,
          columnGroup: 'sidebar',
        },
        {
          id: 'b-side-8',
          type: 'paragraph',
          content: '• English (Fluent / Professional)\n• Hindi (Native / Bilingual)\n• Punjabi (Conversational)\n\nTools: Salesforce CRM, RealPage, MS Excel, AutoCAD Viewer, MagicBricks, 99acres Pro',
          fontSize: 9.5,
          x: 4,
          y: 80,
          width: 27,
          isSpatial: true,
          columnGroup: 'sidebar',
        },

        // 3. Right Main Column (Fixed within 65% Main Container, y >= 18%)
        {
          id: 'b-main-1',
          type: 'h2',
          content: 'PROFESSIONAL SUMMARY',
          align: 'left',
          isBold: true,
          fontSize: 12,
          textColor: '#064e3b',
          x: 39,
          y: 20.5,
          width: 56,
          isSpatial: true,
          columnGroup: 'right',
        },
        {
          id: 'b-main-2',
          type: 'paragraph',
          content: 'Results-driven, RERA-certified Senior Real Estate Consultant with over 9+ years of extensive expertise in driving high-value commercial leasing and premium residential acquisitions. Proven track record of orchestrating over ₹140+ Crores in lifetime property transactions across prime metropolitan corridors. Trusted advisor to Fortune 500 enterprises, corporate tenants, and high-net-worth investors seeking strategic asset positioning, risk mitigation, and seamless closing execution.',
          align: 'justify',
          fontSize: 10,
          x: 39,
          y: 24,
          width: 56,
          isSpatial: true,
          columnGroup: 'right',
        },
        {
          id: 'b-main-3',
          type: 'h2',
          content: 'PROFESSIONAL EXPERIENCE',
          align: 'left',
          isBold: true,
          fontSize: 12,
          textColor: '#064e3b',
          x: 39,
          y: 39.5,
          width: 56,
          isSpatial: true,
          columnGroup: 'right',
        },
        {
          id: 'b-main-4',
          type: 'paragraph',
          content: 'Senior Real Estate Consultant | Prime Horizon Realty Advisory\n2021 – Present | Gurugram, India',
          isBold: true,
          fontSize: 10.5,
          x: 39,
          y: 43,
          width: 56,
          isSpatial: true,
          columnGroup: 'right',
        },
        {
          id: 'b-main-5',
          type: 'bullet',
          content: 'Direct commercial leasing transactions totaling 120,000+ sq. ft. across Golf Course Road and Cyber City business districts.',
          fontSize: 9.5,
          x: 39,
          y: 48,
          width: 56,
          isSpatial: true,
          columnGroup: 'right',
        },
        {
          id: 'b-main-6',
          type: 'bullet',
          content: 'Manage an elite portfolio of 45+ HNI private investors, achieving an average transaction turnaround time 30% faster than industry benchmark.',
          fontSize: 9.5,
          x: 39,
          y: 53,
          width: 56,
          isSpatial: true,
          columnGroup: 'right',
        },
        {
          id: 'b-main-7',
          type: 'bullet',
          content: 'Conduct comprehensive legal due diligence, title clearance, and municipal authority verifications ensuring 100% RERA compliance.',
          fontSize: 9.5,
          x: 39,
          y: 58,
          width: 56,
          isSpatial: true,
          columnGroup: 'right',
        },
        {
          id: 'b-main-8',
          type: 'paragraph',
          content: 'Commercial Property Advisor | Metro Assets Real Estate\n2018 – 2021 | New Delhi, India',
          isBold: true,
          fontSize: 10.5,
          x: 39,
          y: 64,
          width: 56,
          isSpatial: true,
          columnGroup: 'right',
        },
        {
          id: 'b-main-9',
          type: 'bullet',
          content: 'Successfully executed institutional leases for tech unicorns, banking institutions, and co-working operators generating ₹42 Crores in asset value.',
          fontSize: 9.5,
          x: 39,
          y: 69,
          width: 56,
          isSpatial: true,
          columnGroup: 'right',
        },
        {
          id: 'b-main-10',
          type: 'bullet',
          content: 'Formulated tailored market feasibility reports, rental yield analyses, and capital appreciation models for commercial acquisitions.',
          fontSize: 9.5,
          x: 39,
          y: 74,
          width: 56,
          isSpatial: true,
          columnGroup: 'right',
        },
        {
          id: 'b-main-11',
          type: 'h2',
          content: 'REAL ESTATE KNOWLEDGE & TRANSACTION HIGHLIGHTS',
          align: 'left',
          isBold: true,
          fontSize: 12,
          textColor: '#064e3b',
          x: 39,
          y: 71,
          width: 56,
          isSpatial: true,
          columnGroup: 'right',
        },
        {
          id: 'b-main-12',
          type: 'bullet',
          content: 'Closed landmark ₹28 Crore penthouse transaction in DLF Phase 5, securing highest price-per-square-foot in Q3 2024.',
          fontSize: 9.5,
          x: 39,
          y: 75,
          width: 56,
          isSpatial: true,
          columnGroup: 'right',
        },
        {
          id: 'b-main-13',
          type: 'bullet',
          content: 'Awarded "Excellence in Commercial Advisory" by North India Real Estate Forum for three consecutive years (2022, 2023, 2024).',
          fontSize: 9.5,
          x: 39,
          y: 80,
          width: 56,
          isSpatial: true,
          columnGroup: 'right',
        },
      ],
    },
    {
      id: 'page-2',
      pageNumber: 2,
      rotation: 0,
      layoutMode: 'spatial',
      backgroundImageUrl:
        'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="794" height="1123" viewBox="0 0 794 1123"><rect width="794" height="1123" fill="%23ffffff"/><rect x="42" y="45" width="710" height="6" rx="3" fill="%23064e3b"/><rect x="42" y="140" width="710" height="300" rx="8" fill="%23f8fafc" stroke="%23e2e8f0" stroke-width="1.5"/></svg>',
      thumbnailUrl:
        'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="200" height="280" viewBox="0 0 794 1123"><rect width="794" height="1123" fill="%23ffffff"/><rect x="42" y="45" width="710" height="8" rx="4" fill="%23064e3b"/><rect x="42" y="140" width="710" height="300" rx="8" fill="%23f8fafc" stroke="%23e2e8f0" stroke-width="2"/></svg>',
      blocks: [
        {
          id: 'b-2-1',
          type: 'h2',
          content: 'Key Transaction Portfolio & Deal Milestones',
          align: 'left',
          isBold: true,
          fontSize: 16,
          textColor: '#064e3b',
          x: 7,
          y: 6,
          width: 86,
          isSpatial: true,
        },
        {
          id: 'b-2-2',
          type: 'paragraph',
          content: 'Summary of major commercial leasing and luxury residential acquisitions completed under advisory representation:',
          fontSize: 10,
          x: 7,
          y: 11,
          width: 86,
          isSpatial: true,
        },
        {
          id: 'b-2-3',
          type: 'table',
          content: 'Transaction Portfolio Matrix',
          fontSize: 9.5,
          x: 7,
          y: 15,
          width: 86,
          isSpatial: true,
          tableData: {
            headers: ['Property Type', 'Location / Sector', 'Area (Sq. Ft.)', 'Deal Value (₹ INR)', 'Role'],
            rows: [
              ['Commercial Office', 'Cyber City, Gurugram', '45,000 sq.ft', '₹52.5 Crores', 'Exclusive Tenant Rep'],
              ['Luxury Penthouse', 'Golf Course Road', '8,200 sq.ft', '₹28.0 Crores', 'Buyer Advisory & Title'],
              ['Grade-A IT Park', 'Sector 62, Noida', '32,000 sq.ft', '₹38.2 Crores', 'Landlord Advisory'],
              ['High-Street Retail', 'Connaught Place, New Delhi', '6,500 sq.ft', '₹21.4 Crores', 'Lease Structuring'],
            ],
          },
        },
        {
          id: 'b-2-4',
          type: 'h2',
          content: 'Professional References & Compliance Endorsement',
          align: 'left',
          isBold: true,
          fontSize: 14,
          textColor: '#064e3b',
          x: 7,
          y: 48,
          width: 86,
          isSpatial: true,
        },
        {
          id: 'b-2-5',
          type: 'paragraph',
          content: 'All advisory engagements strictly adhere to RERA guidelines, National Real Estate Development Council (NAREDCO) standards, and state property registration protocols.',
          fontSize: 10,
          x: 7,
          y: 54,
          width: 86,
          isSpatial: true,
        },
        {
          id: 'b-2-6',
          type: 'signature',
          content: 'Charanjeet Singh — Senior Real Estate Consultant (RERA-DLR-2021-A-04829)',
          fontSize: 10,
          x: 45,
          y: 68,
          width: 48,
          isSpatial: true,
        },
      ],
    },
  ],
};

// Ensure all sample blocks carry originalContent for double-text ghosting prevention
SAMPLE_DOCUMENT.pages.forEach((p) => {
  p.blocks.forEach((b) => {
    b.originalContent = b.content;
  });
});
